services:
  redis:
    image: redis:latest
    container_name: notification-redis
    ports:
      - "5252:6379"
    volumes:
      - notification_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  notification_redis_data:
    driver: local